- name: External Role Demo
  hosts: servera*
  gather_facts: false
  roles:
    - cisco.catalystwan.health_checks
    - student.bash_env
    - geerlingguy.php
    - web_server
    - community.grafana.grafana
  tasks:
    - name: Get server general information
      cisco.catalystwan.server_info:
        information_category: "server_info"

    - name: Import Redhat Role
      ansible.builtin.import_role:
        name: redhat.rhel_system_roles.timesync
      vars:
        timesync_ntp_servers:
          - hostname: foo.example.com
            maxpoll: 6
          - hostname: bar.example.com
            maxpoll: 6
          - hostname: baz.example.com
