- name: Template Demo
  hosts: servera*
  gather_facts: true
  become: true

  

  tasks:
    - name: Open Firewall Port
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
 
    - name: Install Web Package
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Create Info Html Page
      ansible.builtin.template:
        src: ./j2/simple.j2
        dest: /var/www/html/info.html

    - name: Restart my service
      ansible.builtin.service:
        name: httpd
        state: restarted
